- name: Install firewalld
  hosts: webapp
  remote_user: ec2-user
  become: yes
  gather_facts: yes
  roles:
    - install_firewalld
    
- name: open port 5000 on EC2 instance
  hosts: webapp
  remote_user: ec2-user
  become: yes
  gather_facts: no
  roles:
    - port_open

- name: Install docker
  hosts: webapp
  remote_user: ec2-user
  become: yes
  gather_facts: no
  roles:
    - install_docker

- name: clone git repo
  hosts: webapp
  remote_user: ec2-user
  become: yes
  gather_facts: no
  roles:
    - copy_git_repo
      
- name: build image
  tags: build_image
  hosts: webapp
  remote_user: ec2-user
  become: yes
  gather_facts: no 
  roles:
    - build_image

  vars_prompt:
    - name: docker_image_name
      prompt: "Enter docker image version"
      private: no
      
- name: Start/update Docker Compose services
  tags: docker_compose
  hosts: webapp
  remote_user: ec2-user
  become: yes
  gather_facts: no 
  roles:
    - docker_compose